site_name: SORMAS Stats
repo_name: 'hzi-braunschweig/SORMAS-Stats'
repo_url: 'https://github.com/hzi-braunschweig/SORMAS-Stats'

theme:
  name: material
  features:
  - tabs
  palette:
    primary: 'blue'

extra:
  version: 0.10
  social:
  - icon: 'fontawesome/brands/github-alt'
    link: 'https://github.com/hzi-braunschweig/SORMAS-Stats'
plugins:
- search:
    separator: '[\s]+'

nav:
- Sormas Stats:
  - Sormas Stats: 'index.md'
- Jupyter:
  - 'jupyter.md'
- Python:
  - 'python.md'
- R:
  - R: 'r.md'
- Data:
  - Generation: 'data-gen.md'
  - Migration: 'db.md'
- "Sormas.org": "https://sormas.org"