# Generated by Django 3.1.5 on 2021-03-07 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasesPerDay',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactNetworkNodes',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('group', models.CharField(choices=[('HEALTHY', 'HEALTHY'), ('NOT_CLASSIFIED', 'NOT_CLASSIFIED')], max_length=16)),
                ('shape', models.CharField(choices=[('icon', 'icon')], max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contact', models.BigIntegerField()),
                ('caze_id', models.BigIntegerField()),
                ('disease_contact', models.CharField(max_length=32)),
                ('person_id_contact', models.BigIntegerField()),
                ('lastcontactdate', models.DateField(null=True)),
                ('contactproximity', models.CharField(max_length=32, null=True)),
                ('resultingcase_id', models.BigIntegerField(null=True)),
                ('contactstatus', models.CharField(max_length=32, null=True)),
                ('contactclassification', models.CharField(max_length=32)),
                ('followupstatus', models.CharField(max_length=32)),
                ('relationtocase', models.CharField(max_length=32, null=True)),
                ('reportdate', models.DateField()),
                ('id_cases', models.BigIntegerField()),
                ('person_id_cases', models.BigIntegerField()),
                ('region_id_cases', models.BigIntegerField()),
                ('district_id_cases', models.BigIntegerField()),
                ('caseclassification', models.CharField(max_length=32)),
                ('disease_cases', models.CharField(max_length=32)),
                ('region_id', models.BigIntegerField(null=True)),
                ('region_name', models.CharField(max_length=32, null=True)),
                ('district_id', models.BigIntegerField(null=True)),
                ('district_name', models.CharField(max_length=32, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactNetworkEdges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
                ('dashes', models.CharField(max_length=32)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contactnetworkedges_source', to='stats.contactnetworknodes')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.contactnetworknodes')),
            ],
            options={
                'unique_together': {('source', 'target')},
            },
        ),
    ]
