# Generated by Django 3.1.5 on 2021-01-07 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasesPerDay',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactNetworkNodes',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('group', models.CharField(choices=[('HEALTHY', 'HEALTHY'), ('NOT_CLASSIFIED', 'NOT_CLASSIFIED')], max_length=16)),
                ('shape', models.CharField(choices=[('icon', 'icon')], max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactNetworkEdges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
                ('dashes', models.CharField(max_length=32)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contactnetworkedges_source', to='stats.contactnetworknodes')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.contactnetworknodes')),
            ],
            options={
                'unique_together': {('source', 'target')},
            },
        ),
    ]
